# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fenetre_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(389, 531)
        Dialog.setMinimumSize(QtCore.QSize(389, 531))
        Dialog.setMaximumSize(QtCore.QSize(389, 531))
        self.label_Circuit = QtWidgets.QLabel(Dialog)
        self.label_Circuit.setGeometry(QtCore.QRect(140, 10, 91, 21))
        self.label_Circuit.setObjectName("label_Circuit")
        self.combo_Circuit = QtWidgets.QComboBox(Dialog)
        self.combo_Circuit.setGeometry(QtCore.QRect(20, 10, 111, 23))
        self.combo_Circuit.setObjectName("combo_Circuit")
        self.combo_Circuit.addItem("")
        self.combo_Circuit.addItem("")
        self.txt_Ecrire = QtWidgets.QLineEdit(Dialog)
        self.txt_Ecrire.setGeometry(QtCore.QRect(160, 70, 61, 23))
        self.txt_Ecrire.setObjectName("txt_Ecrire")
        self.btn_InitRAM = QtWidgets.QPushButton(Dialog)
        self.btn_InitRAM.setGeometry(QtCore.QRect(99, 220, 121, 41))
        self.btn_InitRAM.setObjectName("btn_InitRAM")
        self.btn_Lire = QtWidgets.QPushButton(Dialog)
        self.btn_Lire.setGeometry(QtCore.QRect(240, 130, 80, 23))
        self.btn_Lire.setObjectName("btn_Lire")
        self.txt_Adresse = QtWidgets.QLineEdit(Dialog)
        self.txt_Adresse.setGeometry(QtCore.QRect(20, 100, 61, 23))
        self.txt_Adresse.setObjectName("txt_Adresse")
        self.label_Adresse = QtWidgets.QLabel(Dialog)
        self.label_Adresse.setGeometry(QtCore.QRect(90, 100, 61, 21))
        self.label_Adresse.setObjectName("label_Adresse")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 190, 371, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.txt_InitRAM = QtWidgets.QLineEdit(Dialog)
        self.txt_InitRAM.setGeometry(QtCore.QRect(20, 230, 61, 23))
        self.txt_InitRAM.setObjectName("txt_InitRAM")
        self.btn_Ecrire = QtWidgets.QPushButton(Dialog)
        self.btn_Ecrire.setGeometry(QtCore.QRect(240, 70, 80, 23))
        self.btn_Ecrire.setObjectName("btn_Ecrire")
        self.check_Incre = QtWidgets.QCheckBox(Dialog)
        self.check_Incre.setGeometry(QtCore.QRect(230, 220, 111, 21))
        self.check_Incre.setObjectName("check_Incre")
        self.check_Comple = QtWidgets.QCheckBox(Dialog)
        self.check_Comple.setGeometry(QtCore.QRect(230, 240, 121, 21))
        self.check_Comple.setObjectName("check_Comple")
        self.btn_DumpRAM = QtWidgets.QPushButton(Dialog)
        self.btn_DumpRAM.setGeometry(QtCore.QRect(100, 280, 121, 41))
        self.btn_DumpRAM.setObjectName("btn_DumpRAM")
        self.check_EditPlus2 = QtWidgets.QCheckBox(Dialog)
        self.check_EditPlus2.setGeometry(QtCore.QRect(20, 380, 331, 21))
        self.check_EditPlus2.setObjectName("check_EditPlus2")
        self.label_Baudrate = QtWidgets.QLabel(Dialog)
        self.label_Baudrate.setGeometry(QtCore.QRect(120, 420, 81, 21))
        self.label_Baudrate.setObjectName("label_Baudrate")
        self.combo_Baudrate = QtWidgets.QComboBox(Dialog)
        self.combo_Baudrate.setGeometry(QtCore.QRect(20, 420, 91, 23))
        self.combo_Baudrate.setObjectName("combo_Baudrate")
        self.combo_Baudrate.addItem("")
        self.combo_Baudrate.addItem("")
        self.combo_Baudrate.addItem("")
        self.combo_Baudrate.addItem("")
        self.btn_TestRS = QtWidgets.QPushButton(Dialog)
        self.btn_TestRS.setGeometry(QtCore.QRect(20, 470, 91, 41))
        self.btn_TestRS.setObjectName("btn_TestRS")
        self.btn_RX = QtWidgets.QPushButton(Dialog)
        self.btn_RX.setGeometry(QtCore.QRect(150, 470, 51, 41))
        self.btn_RX.setObjectName("btn_RX")
        self.btn_Exit = QtWidgets.QPushButton(Dialog)
        self.btn_Exit.setGeometry(QtCore.QRect(280, 470, 71, 41))
        self.btn_Exit.setObjectName("btn_Exit")
        self.txt_Lire = QtWidgets.QLineEdit(Dialog)
        self.txt_Lire.setGeometry(QtCore.QRect(160, 130, 61, 23))
        self.txt_Lire.setText("")
        self.txt_Lire.setClearButtonEnabled(False)
        self.txt_Lire.setObjectName("txt_Lire")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_Circuit.setText(_translate("Dialog", "Circuit teste"))
        self.combo_Circuit.setItemText(0, _translate("Dialog", "ATMega128"))
        self.combo_Circuit.setItemText(1, _translate("Dialog", "ATMega32"))
        self.txt_Ecrire.setText(_translate("Dialog", "FF"))
        self.btn_InitRAM.setText(_translate("Dialog", "Initialiser la RAM"))
        self.btn_Lire.setText(_translate("Dialog", "Lire"))
        self.txt_Adresse.setText(_translate("Dialog", "3190"))
        self.label_Adresse.setText(_translate("Dialog", "Adresse"))
        self.txt_InitRAM.setText(_translate("Dialog", "FF"))
        self.btn_Ecrire.setText(_translate("Dialog", "Ecrire"))
        self.check_Incre.setText(_translate("Dialog", "Incrementale"))
        self.check_Comple.setText(_translate("Dialog", "Complemente"))
        self.btn_DumpRAM.setText(_translate("Dialog", "Dumper la RAM"))
        self.check_EditPlus2.setText(_translate("Dialog", "Afficher le resultat de la relecture (EditPlus 2)"))
        self.label_Baudrate.setText(_translate("Dialog", "Baudrate"))
        self.combo_Baudrate.setItemText(0, _translate("Dialog", "9600"))
        self.combo_Baudrate.setItemText(1, _translate("Dialog", "19200"))
        self.combo_Baudrate.setItemText(2, _translate("Dialog", "38400"))
        self.combo_Baudrate.setItemText(3, _translate("Dialog", "1000000"))
        self.btn_TestRS.setText(_translate("Dialog", "Test_RS232"))
        self.btn_RX.setText(_translate("Dialog", "RX"))
        self.btn_Exit.setText(_translate("Dialog", "Exit"))
