# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualisation.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(851, 286)
        Dialog.setMinimumSize(QtCore.QSize(851, 286))
        Dialog.setMaximumSize(QtCore.QSize(851, 286))
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 141, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 50, 151, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(300, 50, 421, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 50, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 130, 301, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 40, 111, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 10, 121, 31))
        self.radioButton_3.setObjectName("radioButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(20, 70, 85, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 30, 80, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 210, 41, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 210, 41, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 220, 61, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(450, 220, 81, 31))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(670, 160, 141, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(670, 210, 141, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(670, 110, 141, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(580, 120, 41, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(470, 130, 51, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(530, 130, 31, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.radioButton.toggled['bool'].connect(self.lineEdit.setDisabled)
        self.radioButton_2.toggled['bool'].connect(self.lineEdit.setEnabled)
        self.radioButton.toggled['bool'].connect(self.pushButton.setDisabled)
        self.radioButton_2.toggled['bool'].connect(self.pushButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton.setText(_translate("Dialog", "Resultat courant"))
        self.radioButton_2.setText(_translate("Dialog", "Resultat enregistre"))
        self.pushButton.setText(_translate("Dialog", "Charger fichier"))
        self.radioButton_4.setText(_translate("Dialog", "Differentielle"))
        self.radioButton_3.setText(_translate("Dialog", "Incementale"))
        self.checkBox.setText(_translate("Dialog", "Zoom"))
        self.pushButton_2.setText(_translate("Dialog", "Load"))
        self.pushButton_3.setText(_translate("Dialog", ">"))
        self.pushButton_4.setText(_translate("Dialog", "<"))
        self.lineEdit_2.setText(_translate("Dialog", "1"))
        self.label.setText(_translate("Dialog", "/"))
        self.pushButton_5.setText(_translate("Dialog", "Enregistrer image"))
        self.pushButton_6.setText(_translate("Dialog", "Tout enregistrer"))
        self.pushButton_7.setText(_translate("Dialog", "Graphique de fautes"))
        self.pushButton_8.setText(_translate("Dialog", "Play"))
        self.lineEdit_3.setText(_translate("Dialog", "0.5"))
        self.label_2.setText(_translate("Dialog", "s"))